### PR TITLE
simplify maven-javadoc-plugin

### PR DESCRIPTION
**Pull request by sullis**

### CODE REVIEW

**Comment by sullis** [comment]
LGTM @joel-costigliola

**Comment by scordio** [comment]
@sullis what are you trying to achieve here? As far as I can see, you removed the AssertJ stylesheet from the javadoc generation.

**Comment by joel-costigliola** [comment]
Agreed, we want to keep the javadoc stylesheet

**Comment by joel-costigliola** [comment]
Irrelevant PR

**Pull request closed without merging**
